// <auto-generated />
using System;
using BowelMovementTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BowelMovementTracker.Migrations
{
    [DbContext(typeof(BowelMovementTrackerContext))]
    [Migration("20260214142429_UpdateUserPasswordField")]
    partial class UpdateUserPasswordField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BowelMovementTracker.Data.Diary", b =>
                {
                    b.Property<Guid>("DiaryIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiaryUserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiaryIdentifier");

                    b.ToTable("Diary");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.Log", b =>
                {
                    b.Property<Guid>("LogIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogBowelMovementType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LogDiaryIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LogLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LogWasCoffeeConsumed")
                        .HasColumnType("bit");

                    b.Property<bool>("LogWasMilkConsumed")
                        .HasColumnType("bit");

                    b.HasKey("LogIdentifier");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.User", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserDiaryIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserEmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserIdentifier");

                    b.HasIndex("UserEmailAddress")
                        .IsUnique();

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
