// <auto-generated />
using System;
using BowelMovementTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BowelMovementTracker.Migrations
{
    [DbContext(typeof(BowelMovementTrackerContext))]
    partial class BowelMovementTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BowelMovementTracker.Data.Diary", b =>
                {
                    b.Property<Guid>("DiaryIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("DiaryUserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiaryIdentifier");

                    b.HasIndex("DiaryIdentifier")
                        .IsUnique();

                    b.HasIndex("DiaryUserIdentifier")
                        .IsUnique();

                    b.ToTable("Diary");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.Log", b =>
                {
                    b.Property<Guid>("LogIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<int>("LogBowelMovementType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LogDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("LogDiaryIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LogLastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("LogNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool?>("LogWasCoffeeConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("LogWasMilkConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.HasKey("LogIdentifier");

                    b.HasIndex("LogDiaryIdentifier");

                    b.HasIndex("LogIdentifier")
                        .IsUnique();

                    b.ToTable("Log");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.User", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("UserEmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserIdentifier");

                    b.HasIndex("UserEmailAddress")
                        .IsUnique();

                    b.HasIndex("UserIdentifier")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.Diary", b =>
                {
                    b.HasOne("BowelMovementTracker.Data.User", "User")
                        .WithOne("Diary")
                        .HasForeignKey("BowelMovementTracker.Data.Diary", "DiaryUserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Diary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.Log", b =>
                {
                    b.HasOne("BowelMovementTracker.Data.Diary", "Diary")
                        .WithMany("Logs")
                        .HasForeignKey("LogDiaryIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Log_Diary");

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.Diary", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("BowelMovementTracker.Data.User", b =>
                {
                    b.Navigation("Diary")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
